# 使用 Node.js 官方镜像
FROM node:18

# 设置工作目录
WORKDIR /app

# 安装 cron
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources
RUN apt-get update && apt-get install -y cron

# 复制 Node.js 脚本到容器中
COPY index.js /app/index.js
COPY config.json /app/config.json
COPY storage.json /app/storage.json

# 创建 cron 任务，每分钟运行一次脚本 (根据需要修改时间)
RUN echo "* * * * * /usr/local/bin/node /app/index.js >> /app/cron.log 2>&1" > /etc/cron.d/node-cron-job

# 给 cron 文件添加执行权限
RUN chmod 0644 /etc/cron.d/node-cron-job

# 应用 cron 任务
RUN crontab /etc/cron.d/node-cron-job
RUN touch /app/cron.log
# 启动 cron 服务并保持容器运行
CMD cron && tail -f /app/cron.log
